---
- name: Initialize an empty list for vms
  set_fact:
    empty_list: []
    
- name: Generating VM name(s)
  set_fact: 
    vm_names: "{{ empty_list + [ item ] }}"
  with_sequence: start=1 end="{{ count }}" format="{{ name_format }}"

- debug: var=vm_names
  when: verbose

# Add your own plays here