---
# - name: Initialize an empty list for vms
#   set_fact:
#     empty_list: []

- debug: var="{{vm_names|length}}"
  when: verbose

- name: Generating VM name(s)
  set_fact: 
    vm_names: "{{ vm_names + [ item ] }}"
  with_sequence: start=1 end="{{ count }}" format="{{ name_format }}"
  when: vm_names|length = 0

- debug: var=vm_names
  when: verbose

# Add your own plays here