---
- name: Create resource group
  azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    location: "{{ location }}"
  register: create_resource_group_output
  when: resource_group is defined

- name: Log create_resource_group_output
  debug: 
    var: create_resource_group_output
  when: verbose and create_resource_group_output is defined

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ resource_group }}"
    name: "{{ resource_group }}virtualnetwork"
    address_prefixes: "{{ virtualnetwork_address_prefixes }}"
  register: create_virtual_network_output

- name: Log create_virtual_network_output
  debug: 
    var: create_virtual_network_output
  when: verbose and create_virtual_network_output is defined

- name: Provision Azure Instance
  azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_name }}"
    vm_size: "{{ vm_size }}"
    admin_username: "{{ admin_username }}"
    admin_password: "{{ admin_password }}"
    ssh_public_keys: "{{ ssh_keys }}"
    image:
      offer: "{{ offer }}"
      publisher: "{{ publisher }}"
      sku: "{{ sku }}"
      version: "{{ version }}"
  register: azure_created_vms

- name: Log azure_created_vms
  debug: 
    var: azure_created_vms
  when: verbose

- name: Add new wms to a group
  add_host: 
    name: "{{ item.instance.ipv4 }}"
    groups: azure_hosts
  with_items: "{{ azure_created_vms.results }}"

