---
# azure parameters
location: westus2
resource_group: res_group1
network_name: "{{ resource_group }}-network" 
network_cidr: 10.10.0.0/16
subnet_name: "{{ resource_group }}-subnet"
subnet_cidr: 10.10.0.0/24

# azure image parameters
publisher: OpenLogic
offer: CentOS
version: latest
sku: 7.4

# azure guest parameters
vm_name: vm_name
vm_size: Standard_A1
admin_username: admin
admin_password: password
ssh_keys: 

# enable debugging
verbose: false