---
- name: cfme-backup
  hosts: all
  gather_facts: false
  remote_user: root

  pre_tasks:
    - name: logging manageiq object
      debug: var=manageiq
      when: manageiq is defined

  roles:
    - { role: cfme-backup }


