---
- name: Provision VMware Instances
  vmware_guest:
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    name: "{{ item }}"
    template: "{{ template }}"
    datacenter: "{{ datacenter }}"
    cluster: "{{ cluster }}"
    folder: "{{ folder }}"
    snapshot_src: "{{ snapshot }}"
    linked_clone: "{{ linked_clone }}"
    notes: "{{ notes }}"
    hardware:
      memory_mb: "{{ memory_mb }}"
      num_cpus: "{{ num_cpus }}"
    wait_for_ip_address: "{{ wait_for_ip_address }}"
    networks:
      - name: "{{ vlan }}"
        device_type: vmxnet3
        type: dhcp
        # ip: 
        # netmask: 
        # mac:
        # gateway:
        # dns_servers: # DNS servers for this network interface (Windows)
        # domain:  # Domain name for this network interface (Windows)
    state: poweredon
  delegate_to: localhost
  with_items: "{{ vm_names }}"
  register: vms

- name: Log vms output
  debug: 
    var: item
  with_items: "{{ vms }}"
  when: verbose